### ISSUE TITLE
Redactar la inicialización de la Wiki.

### ISSUE THREAD

**Issue by almo** [Team4Rookies/GalsTech#1]
Instrucciones:
  + Revisar la descripción del grupo. Si tienes algún comentario inclúyelo en el hilo del issue y pasa al siguiente punto. 
  + Modifica la lista de miembros del equipo para incluir tu identificador de GitHub. Sería conveniente que tengas un perfil completado.

Tras esto, marca tu nombre de abajo:

- [x] almo
- [ ] Merchy
- [x] aidawhale
- [x] anagiadas
- [x] Beatriz MM
- [x] celtiaml
- [x] Icia Carro Barallobre
- [x] Lucía María Álvarez Crespo
- [x] paloma
- [ ] veropduro

**Comment by luciamariaalvarezcrespo** [comment]
Hola, cómo se modifica la wiki del equipo? Saludos!

**Comment by almo** [comment]
Hola Lucia, 

1. Accede a la [wiki del equipo](https://github.com/Team4Rookies/GalsTech/wiki). 
2. En la parte superior derecha tienes un botón para activar el modo edición.
3. Modifica el contenido de la wiki usando markdown. Consulta la [guía de markdown](https://guides.github.com/features/mastering-markdown/) para entender la sintaxis.
4. Una vez completada, guarda el contenido usando el botón de la parte inferior, añadiendo un comentario sobre los cambios introducidos.

Más información sobre el uso de la wiki en la [guía de la wiki](https://docs.github.com/en/github/building-a-strong-community/documenting-your-project-with-wikis) 

Puedes repasar las guías que te he pasado y crear unas notas para comenzar con la documentación sobre GitHub. Esto lo puedes hacer en una página de la wiki de manera temporal o crear tu fichero en el [repositorio](https://github.com/Team4Rookies/GalsTech). 

Y no te preocupes de romper nada.... GitHub guarda el histórico de todo, así que siempre lo podemos recuperar.

Avisa si tienes más dudas.

**Comment by almo** [comment]
Prueba ahora.

**Comment by anagiadas** [comment]
Ahora ya me aparece el botón y pude modificar la wiki sin problema. Gracias!!
